{
 "title": "Übersicht",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "etappe",
    "label": "Etappe",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"heizung\",\n    tag: \"etappe\",\n    predicate: (r) => true,\n    start: -1d\n)\n"
   },
   {
    "name": "haus",
    "label": "Haus",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"heizung\",\n    tag: \"haus\",\n    predicate: (r) => r.etappe =~ /^${etappe:regex}$/,\n    start: -1d\n)"
   },
   { "name": "unten_mitte_oben", "query": "unten, mitte, oben" },
   {
    "name": "field_keys",
    "label": "Field Keys",
    "query": "import \"influxdata/influxdb/schema\"\n\n// List buckets\nschema.fieldKeys(bucket: \"heizung\")"
   },
   {
    "name": "position",
    "label": "Position",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"heizung\",\n    tag: \"position\",\n    predicate: (r) => true,\n    start: -1d\n)\n\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperaturen Speicher",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  //|> filter(fn: (r) => r[\"_field\"] =~ /^sp_(unten|mitte|oben)_temperature_C$/)\n  //|> filter(fn: (r) => r[\"_field\"] =~ /^sp_{unten_mitte_oben:regex}_temperature_C$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^sp_(${unten_mitte_oben})_temperature_C$/)\n  //|> filter(fn: (r) => r[\"_field\"] =~ /^${field_keys:regex}$/) // Versuch Peter\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Ladung Speicher",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^ladung_.*_prozent$/)\n  //|> filter(fn: (r) => r[\"_field\"] =~ /^${field_keys:regex}$/) // versuch Peter\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Verbrauch Speicher (grob geschaetzt)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"sp_verbrauch_W\" or r[\"_field\"] == \"sp_verbrauch_W\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperaturen Speicher nur mitte",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^sp_mitte_temperature_C$/)\n  //|> filter(fn: (r) => r[\"_field\"] =~ /^${field_keys:regex}$/) // Versuch Peter\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Puent: Anforderung und Zwangsladung, alte Heizung, gemessen",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"rutschbahnhaus\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"pico_ria\")\r\n//  |> filter(fn: (r) => r[\"_field\"] == \"anforderung\" or  r[\"_field\"] == \"zwangsladung\")\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"pico_ria\" and r[\"_field\"] == \"anforderung\" or  r[\"_field\"] == \"zwangsladung\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> yield(name: \"distinct\")"
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "friendly_name" ], "type": "tag" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "friendly_name", "operator": "=~", "value": "/.*fern*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/:*speich*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/.*OpenWeatherMap Temp*/" }
     ]
    }
   ]
  },
  {
   "title": "Bochs: Anforderung und Zwangsladung, alte Heizung (gemessen)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"rutschbahnhaus\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"pico_anna\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"anforderung\" or  r[\"_field\"] == \"zwangsladung\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> yield(name: \"distinct\")"
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "friendly_name" ], "type": "tag" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "friendly_name", "operator": "=~", "value": "/.*fern*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/:*speich*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/.*OpenWeatherMap Temp*/" }
     ]
    }
   ]
  },
  {
   "title": "Temporaer Puent, WHILE_HARGASSNER: Anforderung durch Software",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"hsm_zentral_relais_6_pumpe_ein\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DS18 errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^sp_(unten|mitte|oben)_error_C$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Valve open (simulation)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"relais_valve_open_float\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Zentral Pumpe (simulation)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"hsm_zentral_relais_6_pumpe_ein\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Hsm",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"hsm_state_value\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Zentral Hsm",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"hsm_zentral_state_value\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Modbus History Percent OK",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"modbus_ok_percent\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Pico Uptime s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 119 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime_s\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}