{
 "title": "Übersicht",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "etappe",
    "label": "Etappe",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"heizung\",\n    tag: \"etappe\",\n    predicate: (r) => true,\n    start: -1d\n)\n"
   },
   {
    "name": "haus",
    "label": "Haus",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"heizung\",\n    tag: \"haus\",\n    predicate: (r) => r.etappe =~ /^${etappe:regex}$/,\n    start: -1d\n)"
   },
   { "name": "unten_mitte_oben", "query": "unten, mitte, oben" },
   {
    "name": "field_keys",
    "label": "Field Keys",
    "query": "import \"influxdata/influxdb/schema\"\n\n// List buckets\nschema.fieldKeys(bucket: \"heizung\")"
   },
   {
    "name": "position",
    "label": "Position",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"heizung\",\n    tag: \"position\",\n    predicate: (r) => true,\n    start: -1d\n)\n\n"
   },
   { "name": "query0" },
   {
    "name": "verbrauch",
    "query": "sp_verbrauch_W, sp_verbrauch_avg_W"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperaturen Speicher dezentral",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  //|> filter(fn: (r) => r._field =~ /^sp_(unten|mitte|oben)_temperature_C$/)\n  //|> filter(fn: (r) => r._field =~ /^sp_{unten_mitte_oben:regex}_temperature_C$/)\n  |> filter(fn: (r) => r._field =~ /^sp_(${unten_mitte_oben})_temperature_C$/)\n  //|> filter(fn: (r) => r._field =~ /^${field_keys:regex}$/) // Versuch Peter\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Ladung Speicher dezentral",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^ladung_.*_prozent$/)\n  //|> filter(fn: (r) => r._field =~ /^${field_keys:regex}$/) // versuch Peter\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperaturen zentral",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^zentral_(temperature|error)_/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Ladung Speicher zentral",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^sp_ladung_zentral.*_prozent$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Valve open",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"relais_valve_open_float\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Zentral Pumpe",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"hsm_zentral_pumpe_ein\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mischventil",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^mischventil_(stellwert|credit)_/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mischventil Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^mischventil_power_W$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mischventil Fluss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^mischventil_fluss_m3_h$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "relais",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field =~ /^relais_[0-9]/)\r\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\r\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  // |> yield(name: \"mean\")"
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "friendly_name" ], "type": "tag" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "friendly_name", "operator": "=~", "value": "/.*fern*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/:*speich*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/.*OpenWeatherMap Temp*/" }
     ]
    }
   ]
  },
  {
   "title": "Dezentral Hsm",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"hsm_state_value\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Zentral Hsm",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"hsm_zentral_state_value\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Verbrauch Speicher (grob geschaetzt)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  //|> filter(fn: (r) => r._field == \"sp_verbrauch_W\" or r._field == \"sp_verbrauch_avg_W\")\n  |> filter(fn: (r) => r._field =~ /^${verbrauch:regex}$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Wärmezähler - Energie E1-E3",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"dezentral_mbus_tmp_energy_E1_minus_E3_Wh\")\n  // |> filter(fn: (r) => r._field =~ /^dezentral_mbus_tmp_energy_.*(E1|E3)_Wh$/)\n  // |> filter(fn: (r) => r._field =~ /^dezentral_mbus_tmp_/)\n  // |> filter(fn: (r) => r._field != \"dezentral_mbus_tmp_relais_valve_open\")\n  // |> filter(fn: (r) => r._field != \"dezentral_mbus_tmp_valve_open\")\n  // |> filter(fn: (r) => r._field != \"dezentral_mbus_tmp_time_s\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Wärmezähler - Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // |> filter(fn: (r) => r._field =~ /^dezentral_mbus_tmp_energy_E(1|3)_Wh$/)\n  |> filter(fn: (r) => r._field == \"dezentral_mbus_tmp_power_W\")\n  // |> filter(fn: (r) => r._field != \"dezentral_mbus_tmp_relais_valve_open\")\n  // |> filter(fn: (r) => r._field != \"dezentral_mbus_tmp_valve_open\")\n  // |> filter(fn: (r) => r._field != \"dezentral_mbus_tmp_time_s\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Wärmezähler - Vor- und Rücklauftemperatur",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^dezentral_mbus_tmp_temperature_t(1|2)_C$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Wärmezähler - Flow",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"dezentral_mbus_tmp_flow_v1_m3h\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DS18 error_C",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 152 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^sp_(unten|mitte|oben)_error_C$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DS18 onewire ok_percent (100% not shown)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^sp_(unten|mitte|oben)_(a|b)_ok_percent$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Modbus History Percent OK (100% not shown)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 162 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"modbus_ok_percent\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Pico Uptime s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 167 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"uptime_s\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Dezentral Legionellen next",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"next_legionellen_kill_d\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Puent: Anforderung und Zwangsladung, alte Heizung, gemessen",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"rutschbahnhaus\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"pico_ria\")\r\n//  |> filter(fn: (r) => r._field == \"anforderung\" or  r._field == \"zwangsladung\")\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"pico_ria\" and r._field == \"anforderung\" or  r._field == \"zwangsladung\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> yield(name: \"distinct\")"
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "friendly_name" ], "type": "tag" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "friendly_name", "operator": "=~", "value": "/.*fern*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/:*speich*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/.*OpenWeatherMap Temp*/" }
     ]
    }
   ]
  },
  {
   "title": "Bochs: Anforderung und Zwangsladung, alte Heizung (gemessen)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"rutschbahnhaus\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"pico_anna\")\r\n  |> filter(fn: (r) => r._field == \"anforderung\" or  r._field == \"zwangsladung\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> yield(name: \"distinct\")"
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "friendly_name" ], "type": "tag" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "friendly_name", "operator": "=~", "value": "/.*fern*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/:*speich*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/.*OpenWeatherMap Temp*/" }
     ]
    }
   ]
  }
 ]
}