{
 "title": "Übersicht",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "etappe",
    "label": "Etappe",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"heizung\",\n    tag: \"etappe\",\n    predicate: (r) => true,\n    start: -1d\n)\n"
   },
   {
    "name": "haus",
    "label": "Haus",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"heizung\",\n    tag: \"haus\",\n    predicate: (r) => r.etappe =~ /^${etappe:regex}$/,\n    start: -1d\n)"
   },
   {
    "name": "reihe",
    "label": "Hausreihe",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"heizung\",\n    tag: \"reihe\",\n    predicate: (r) => r.etappe =~ /^${etappe:regex}$/,\n    start: -1d\n)"
    }
   },
   { "name": "unten_mitte_oben", "query": "unten, mitte, oben" },
   {
    "name": "LadungDezentral",
    "query": "heizung, baden, minimum, individuell"
   },
   {
    "name": "verbrauch",
    "query": "sp_verbrauch_W, sp_verbrauch_avg_W"
   }
  ]
 },
 "panels": [
  {
   "title": "Übersicht",
   "type": "timeseries",
   "description": "brenner uebersicht: \n-3 saugen\n-10... brenner startet\n-20: auto, brennt nicht\n-30: ausgeschaltet durch Benutzer\n-40: Asche voll\n-50: keine Pellets\n-60: Stoerung\n-100: kein Modbus: ausgeschaltet mit Hauptschalter\n-200: Programmierfehler\n",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  //|> filter(fn: (r) =>  r._field =~ /^sp_ladung_zentral.*_level_prozent$/ or r._field =~ /^sp_ladung_zentral.*_prozent$/ or r._field =~ /^brenner_(1|2)_uebersicht_prozent$/  or r._field =~ /^haeuser_ladung_minimum_prozent$/ or r._field =~ /^_brenner_(1|2)_modulation_soll_prozent$/ or r._field == \"haeuser_ladung_avg_prozent\")\n  |> filter(fn: (r) =>  r._field =~ /^sp_ladung_zentral_prozent$/ or r._field =~ /^brenner_(1|2)_uebersicht_prozent$/  or r._field =~ /^haeuser_ladung_minimum_prozent$/ or r._field =~ /^_brenner_(1|2)_modulation_soll_prozent$/ or r._field == \"haeuser_ladung_avg_prozent\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"distinct\")"
    }
   ]
  },
  {
   "title": "Action Timer minuten",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>  r._field =~ /^actiontimer.*_min$/ or r._field =~ /^*_valve_open_count$/ or r._field == \"sp_zentral_steigung\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"distinct\")"
    }
   ]
  },
  {
   "title": "Dezentral Valve open",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"relais_valve_open_float\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Energie Fernleitung zu Hausreihe",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^hausreihe.*kWh$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperaturen Speicher dezentral",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  //|> filter(fn: (r) => r._field =~ /^sp_(unten|mitte|oben)_temperature_C$/)\n  //|> filter(fn: (r) => r._field =~ /^sp_{unten_mitte_oben:regex}_temperature_C$/)\n  |> filter(fn: (r) => r._field =~ /^sp_(${unten_mitte_oben})_temperature_C$/)\n  //|> filter(fn: (r) => r._field =~ /^${field_keys:regex}$/) // Versuch Peter\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Ladung Speicher dezentral",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  //|> filter(fn: (r) => r._field =~ /^ladung_.*_prozent$/)\n  |> filter(fn: (r) => r._field =~ /^ladung_${LadungDezentral}_prozent$/)\n  //|> filter(fn: (r) => r._field =~ /^ladung_(${LadungDezentral})*_prozent$/)\n  //|> filter(fn: (r) => r._field =~ /^${field_keys:regex}$/) // versuch Peter\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperaturen zentral",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^zentral_(temperature|error)_/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mischventil",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^mischventil_(stellwert|credit)_/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Zentral Pumpe",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"hsm_zentral_pumpe_ein\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mischventil Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^mischventil_power_W$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mischventil Fluss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^mischventil_fluss_m3_h$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "relais",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field =~ /^relais_[0-9]/)\r\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\r\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  // |> yield(name: \"mean\")"
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "friendly_name" ], "type": "tag" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "friendly_name", "operator": "=~", "value": "/.*fern*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/:*speich*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/.*OpenWeatherMap Temp*/" }
     ]
    }
   ]
  },
  {
   "title": "Dezentral Hsm",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"hsm_state_value\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Zentral Hsm",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"hsm_zentral_state_value\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  // |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Verbrauch Speicher (grob geschaetzt)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  //|> filter(fn: (r) => r._field == \"sp_verbrauch_W\" or r._field == \"sp_verbrauch_avg_W\")\n  |> filter(fn: (r) => r._field =~ /^${verbrauch:regex}$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Wärmezähler - Energie E1-E3",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^mbus_.*energy_E1_minus_E3_Wh$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  //|> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n//|> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Wärmezähler - Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^mbus_.*power_W$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  //|> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n//|> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Wärmezähler - Vor- und Rücklauftemperatur",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^mbus_dezentral_temperature_t(1|2)_C$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Wärmezähler - Flow",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"mbus_dezentral_flow_v1_m3h\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DS18 error_C",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 176 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^sp_(unten|mitte|oben)_error_C$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DS18 onewire ok_percent (100% not shown)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^sp_(unten|mitte|oben)_(a|b)_ok_percent$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Modbus History Percent OK (100% not shown)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 186 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"modbus_ok_percent\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dezentral Pico Uptime s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 191 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"uptime_s\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Dezentral Legionellen next",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"next_legionellen_kill_d\")\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> filter(fn: (r) => r.haus =~ /^${haus:regex}$/)\n  |> filter(fn: (r) => r.reihe =~ /^${reihe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Puent: Anforderung und Zwangsladung, alte Heizung, gemessen",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"rutschbahnhaus\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"pico_ria\")\r\n//  |> filter(fn: (r) => r._field == \"anforderung\" or  r._field == \"zwangsladung\")\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"pico_ria\" and r._field == \"anforderung\" or  r._field == \"zwangsladung\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> yield(name: \"distinct\")"
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "friendly_name" ], "type": "tag" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "friendly_name", "operator": "=~", "value": "/.*fern*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/:*speich*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/.*OpenWeatherMap Temp*/" }
     ]
    }
   ]
  },
  {
   "title": "Bochs: Anforderung und Zwangsladung, alte Heizung (gemessen)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"rutschbahnhaus\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"pico_anna\")\r\n  |> filter(fn: (r) => r._field == \"anforderung\" or  r._field == \"zwangsladung\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> yield(name: \"distinct\")"
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "friendly_name" ], "type": "tag" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "friendly_name", "operator": "=~", "value": "/.*fern*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/:*speich*/" },
      { "condition": "OR", "key": "friendly_name", "operator": "=~", "value": "/.*OpenWeatherMap Temp*/" }
     ]
    }
   ]
  },
  {
   "title": "Oekofen Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^temp_oekofen_.*_C$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Oekofen divers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field =~ /^temp_oekofen_.*_MODE$/ or r._field =~ /^temp_oekofen_.*MODULATION_PROCENT$/ or r._field =~ /^temp_oekofen_.*_STATE$/  or r._field =~ /^temp_oekofen_.*_CONTR$/  or r._field =~ /^temp_oekofen_.*RUNTIME$/)\n  |> filter(fn: (r) => r.etappe =~ /^${etappe:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}